# Generated by Django 2.0.6 on 2020-03-16 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAdmin',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 't_admin',
            },
        ),
        migrations.CreateModel(
            name='TClass',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('academy', models.CharField(blank=True, max_length=50, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'db_table': 't_class',
            },
        ),
        migrations.CreateModel(
            name='TClassSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TClass')),
            ],
            options={
                'db_table': 't_class_selected',
            },
        ),
        migrations.CreateModel(
            name='TEvaluation',
            fields=[
                ('eval_id', models.IntegerField(primary_key=True, serialize=False)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TClass')),
            ],
            options={
                'db_table': 't_evaluation',
            },
        ),
        migrations.CreateModel(
            name='TEvaluationDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.IntegerField(blank=True, null=True)),
                ('text2', models.IntegerField(blank=True, null=True)),
                ('text3', models.IntegerField(blank=True, null=True)),
                ('text4', models.IntegerField(blank=True, null=True)),
                ('text5', models.CharField(blank=True, max_length=50, null=True)),
                ('eval_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TEvaluation')),
            ],
            options={
                'db_table': 't_evaluation_detail',
            },
        ),
        migrations.CreateModel(
            name='TExam',
            fields=[
                ('exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TClass')),
            ],
            options={
                'db_table': 't_exam',
            },
        ),
        migrations.CreateModel(
            name='TGradeExam',
            fields=[
                ('grade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('exam_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_gradeexam',
            },
        ),
        migrations.CreateModel(
            name='TGradeSigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TGradeExam')),
            ],
            options={
                'db_table': 't_grade_signed',
            },
        ),
        migrations.CreateModel(
            name='TNotice',
            fields=[
                ('notice_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TAdmin')),
            ],
            options={
                'db_table': 't_notice',
            },
        ),
        migrations.CreateModel(
            name='TScore',
            fields=[
                ('score_id', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TClass')),
            ],
            options={
                'db_table': 't_score',
            },
        ),
        migrations.CreateModel(
            name='TStu',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('native', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('entrance', models.DateField(blank=True, null=True)),
                ('academy', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=50, null=True)),
                ('sclass', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 't_stu',
            },
        ),
        migrations.CreateModel(
            name='TTeacher',
            fields=[
                ('teacher_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('native', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('diplomas', models.CharField(blank=True, max_length=20, null=True)),
                ('politics', models.CharField(blank=True, max_length=20, null=True)),
                ('entrance', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=20, null=True)),
                ('academy', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 't_teacher',
            },
        ),
        migrations.AddField(
            model_name='tscore',
            name='stu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TStu'),
        ),
        migrations.AddField(
            model_name='tgradesigned',
            name='stu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TStu'),
        ),
        migrations.AddField(
            model_name='texam',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TTeacher'),
        ),
        migrations.AddField(
            model_name='tevaluationdetail',
            name='stu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TStu'),
        ),
        migrations.AddField(
            model_name='tevaluation',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TTeacher'),
        ),
        migrations.AddField(
            model_name='tclassselected',
            name='stu_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TStu'),
        ),
        migrations.AddField(
            model_name='tclass',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginapp.TTeacher'),
        ),
    ]
